### ISSUE TITLE
Installation on Centos gives error

### ISSUE THREAD

**Issue by pradippillai** [SGrondin/oracle-orm#2]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'oracle-orm' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose install initial load of /root/nodejs/package.json
5 warn package.json nodejs@1.0.0 No repository field.
6 warn package.json nodejs@1.0.0 No README data
7 verbose installManyTop reading scoped package data from /root/nodejs/node_modules/async/package.json
8 verbose installManyTop reading scoped package data from /root/nodejs/node_modules/coffee/package.json
9 verbose installManyTop reading scoped package data from /root/nodejs/node_modules/mocha/package.json
10 verbose installManyTop reading scoped package data from /root/nodejs/node_modules/nvm/package.json
11 verbose installManyTop reading scoped package data from /root/nodejs/node_modules/oracledb/package.json
12 verbose installManyTop reading scoped package data from /root/nodejs/node_modules/should/package.json
13 info package.json nvm@0.0.3 license should be a valid SPDX license expression
14 verbose readDependencies loading dependencies from /root/nodejs/package.json
15 silly cache add args [ 'oracle-orm', null ]
16 verbose cache add spec oracle-orm
17 silly cache add parsed spec { raw: 'oracle-orm',
17 silly cache add   scope: null,
17 silly cache add   name: 'oracle-orm',
17 silly cache add   rawSpec: '',
17 silly cache add   spec: '_',
17 silly cache add   type: 'range' }
18 silly addNamed oracle-orm@_
19 verbose addNamed "_" is a valid semver range for oracle-orm
20 silly addNameRange { name: 'oracle-orm', range: '_', hasData: false }
21 silly mapToRegistry name oracle-orm
22 silly mapToRegistry using default registry
23 silly mapToRegistry registry https://registry.npmjs.org/
24 silly mapToRegistry uri https://registry.npmjs.org/oracle-orm
25 verbose addNameRange registry:https://registry.npmjs.org/oracle-orm not in flight; fetching
26 verbose request uri https://registry.npmjs.org/oracle-orm
27 verbose request no auth needed
28 info attempt registry request try #1 at 8:50:02 AM
29 verbose request id 3a8820a0565d85d9
30 verbose etag "9UUCUFQH9GS6NZ8FJ4FJLBQ6U"
31 http request GET https://registry.npmjs.org/oracle-orm
32 http 304 https://registry.npmjs.org/oracle-orm
33 silly get cb [ 304,
33 silly get   { date: 'Wed, 18 Nov 2015 08:50:02 GMT',
33 silly get     via: '1.1 varnish',
33 silly get     'cache-control': 'max-age=60',
33 silly get     etag: '"9UUCUFQH9GS6NZ8FJ4FJLBQ6U"',
33 silly get     age: '0',
33 silly get     connection: 'keep-alive',
33 silly get     'x-served-by': 'cache-sin6927-SIN',
33 silly get     'x-cache': 'MISS',
33 silly get     'x-cache-hits': '0',
33 silly get     'x-timer': 'S1447836602.724107,VS0,VE974',
33 silly get     vary: 'Accept' } ]
34 verbose etag https://registry.npmjs.org/oracle-orm from cache
35 verbose get saving oracle-orm to /root/.npm/registry.npmjs.org/oracle-orm/.cache.json
36 silly addNameRange number 2 { name: 'oracle-orm', range: '_', hasData: true }
37 silly addNameRange versions [ 'oracle-orm',
37 silly addNameRange   [ '0.0.1',
37 silly addNameRange     '0.0.2',
37 silly addNameRange     '0.0.3',
37 silly addNameRange     '0.0.4',
37 silly addNameRange     '0.0.5',
37 silly addNameRange     '0.0.6',
37 silly addNameRange     '0.1.0',
37 silly addNameRange     '0.1.1',
37 silly addNameRange     '0.1.2',
37 silly addNameRange     '0.1.3',
37 silly addNameRange     '0.1.4',
37 silly addNameRange     '0.1.5',
37 silly addNameRange     '0.1.6',
37 silly addNameRange     '0.1.7',
37 silly addNameRange     '0.1.8',
37 silly addNameRange     '0.1.9' ] ]
38 silly addNamed oracle-orm@0.1.9
39 verbose addNamed "0.1.9" is a plain semver version for oracle-orm
40 silly cache afterAdd oracle-orm@0.1.9
41 verbose afterAdd /root/.npm/oracle-orm/0.1.9/package/package.json not in flight; writing
42 verbose afterAdd /root/.npm/oracle-orm/0.1.9/package/package.json written
43 silly install resolved [ { name: 'oracle-orm',
43 silly install resolved     version: '0.1.9',
43 silly install resolved     description: 'An Oracle ORM that actually works',
43 silly install resolved     main: 'lib/index.js',
43 silly install resolved     scripts:
43 silly install resolved      { test: 'node lib/unittests.js',
43 silly install resolved        preinstall: './driver/reinstall.sh' },
43 silly install resolved     repository:
43 silly install resolved      { type: 'git',
43 silly install resolved        url: 'git+https://github.com/SGrondin/oracle-orm.git' },
43 silly install resolved     keywords: [ 'oracle', 'orm' ],
43 silly install resolved     author: { name: 'Simon Grondin' },
43 silly install resolved     license: 'MIT',
43 silly install resolved     bugs: { url: 'https://github.com/SGrondin/oracle-orm/issues' },
43 silly install resolved     devDependencies:
43 silly install resolved      { 'coffee-script': '1.7.x',
43 silly install resolved        streamline: '0.10.x',
43 silly install resolved        oracle: '0.3.x' },
43 silly install resolved     homepage: 'https://github.com/SGrondin/oracle-orm',
43 silly install resolved     _id: 'oracle-orm@0.1.9',
43 silly install resolved     _shasum: '229f9395163d4b2c5b6431ba5a749cebc0510177',
43 silly install resolved     _from: 'oracle-orm@_',
43 silly install resolved     _npmVersion: '1.4.10',
43 silly install resolved     _npmUser: { name: 'sgrondin', email: 'jobs@simongrondin.name' },
43 silly install resolved     maintainers: [ [Object] ],
43 silly install resolved     dist:
43 silly install resolved      { shasum: '229f9395163d4b2c5b6431ba5a749cebc0510177',
43 silly install resolved        tarball: 'http://registry.npmjs.org/oracle-orm/-/oracle-orm-0.1.9.tgz' },
43 silly install resolved     directories: {},
43 silly install resolved     _resolved: 'https://registry.npmjs.org/oracle-orm/-/oracle-orm-0.1.9.tgz',
43 silly install resolved     readme: 'ERROR: No README data found!' } ]
44 info install oracle-orm@0.1.9 into /root/nodejs
45 info installOne oracle-orm@0.1.9
46 verbose installOne of oracle-orm to /root/nodejs not in flight; installing
47 verbose lock using /root/.npm/_locks/oracle-orm-0e580475ce53d0c5.lock for /root/nodejs/node_modules/oracle-orm
48 silly install write writing oracle-orm 0.1.9 to /root/nodejs/node_modules/oracle-orm
49 verbose unbuild node_modules/oracle-orm
50 silly gentlyRm /root/nodejs/node_modules/oracle-orm is being purged from base /root/nodejs
51 verbose gentlyRm don't care about contents; nuking /root/nodejs/node_modules/oracle-orm
52 verbose tar unpack /root/.npm/oracle-orm/0.1.9/package.tgz
53 verbose tar unpacking to /root/nodejs/node_modules/oracle-orm
54 silly gentlyRm /root/nodejs/node_modules/oracle-orm is being purged
55 verbose gentlyRm don't care about contents; nuking /root/nodejs/node_modules/oracle-orm
56 silly gunzTarPerm modes [ '755', '644' ]
57 silly gunzTarPerm extractEntry package.json
58 silly gunzTarPerm extractEntry .npmignore
59 silly gunzTarPerm extractEntry README.md
60 silly gunzTarPerm extractEntry LICENSE
61 silly gunzTarPerm extractEntry driver/exports.sh
62 silly gunzTarPerm extractEntry driver/reinstall.sh
63 silly gunzTarPerm extractEntry testDB.json
64 silly gunzTarPerm extractEntry src/Column.coffee
65 silly gunzTarPerm extractEntry src/ORM._coffee
66 silly gunzTarPerm extractEntry src/Query._coffee
67 silly gunzTarPerm extractEntry src/Row._coffee
68 silly gunzTarPerm extractEntry src/Table._coffee
69 silly gunzTarPerm extractEntry src/helpers.coffee
70 silly gunzTarPerm extractEntry src/index.coffee
71 silly gunzTarPerm extractEntry src/types.coffee
72 silly gunzTarPerm extractEntry src/unittests._coffee
73 silly gunzTarPerm extractEntry TODO
74 silly gunzTarPerm extractEntry recompile.sh
75 silly gunzTarPerm extractEntry lib/Column.js
76 silly gunzTarPerm extractEntry lib/ORM.js
77 silly gunzTarPerm extractEntry lib/Query.js
78 silly gunzTarPerm extractEntry lib/Row.js
79 silly gunzTarPerm extractEntry lib/Table.js
80 silly gunzTarPerm extractEntry lib/helpers.js
81 silly gunzTarPerm extractEntry lib/index.js
82 silly gunzTarPerm extractEntry lib/types.js
83 silly gunzTarPerm extractEntry lib/unittests.js
84 verbose write writing to /root/nodejs/node_modules/oracle-orm/package.json
85 info preinstall oracle-orm@0.1.9
86 verbose unsafe-perm in lifecycle false
87 info oracle-orm@0.1.9 Failed to exec preinstall script
88 verbose unlock done using /root/.npm/_locks/oracle-orm-0e580475ce53d0c5.lock for /root/nodejs/node_modules/oracle-orm
89 verbose stack Error: oracle-orm@0.1.9 preinstall: `./driver/reinstall.sh`
89 verbose stack Exit status 1
89 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
89 verbose stack     at EventEmitter.emit (events.js:110:17)
89 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
89 verbose stack     at ChildProcess.emit (events.js:110:17)
89 verbose stack     at maybeClose (child_process.js:1015:16)
89 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
90 verbose pkgid oracle-orm@0.1.9
91 verbose cwd /root/nodejs
92 error Linux 2.6.32-573.8.1.el6.x86_64
93 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "oracle-orm"
94 error node v0.12.7
95 error npm  v2.11.3
96 error code ELIFECYCLE
97 error oracle-orm@0.1.9 preinstall: `./driver/reinstall.sh`
97 error Exit status 1
98 error Failed at the oracle-orm@0.1.9 preinstall script './driver/reinstall.sh'.
98 error This is most likely a problem with the oracle-orm package,
98 error not with npm itself.
98 error Tell the author that this fails on your system:
98 error     ./driver/reinstall.sh
98 error You can get their info via:
98 error     npm owner ls oracle-orm
98 error There is likely additional logging output above.
99 verbose exit [ 1, true ]
100 verbose unbuild node_modules/oracle-orm
101 info preuninstall oracle-orm@0.1.9
102 info uninstall oracle-orm@0.1.9
103 verbose unbuild rmStuff oracle-orm@0.1.9 from /root/nodejs/node_modules
104 info postuninstall oracle-orm@0.1.9
105 silly gentlyRm /root/nodejs/node_modules/oracle-orm is being purged from base /root/nodejs
106 verbose gentlyRm don't care about contents; nuking /root/nodejs/node_modules/oracle-orm
107 silly vacuum-fs purging /root/nodejs/node_modules/oracle-orm
108 silly vacuum-fs quitting because other entries in /root/nodejs/node_modules

**Comment by pradippillai** [comment]
On the installation line this is the error

> oracle@0.3.8 install /root/nodejs/node_modules/oracle-orm/node_modules/oracle
> node-gyp rebuild

make: Entering directory `/root/nodejs/node_modules/oracle-orm/node_modules/oracle/build'
  CXX(target) Release/obj.target/oracle_bindings/src/connection.o
In file included from ../src/connection.cpp:4:
../src/commitBaton.h: In destructor 'CommitBaton::~CommitBaton()':
../src/commitBaton.h:14: error: 'class v8::Persistent<v8::Function, v8::NonCopyablePersistentTraits<v8::Function> >' has no member named 'Dispose'
In file included from ../src/connection.cpp:5:
../src/rollbackBaton.h: In destructor 'RollbackBaton::~RollbackBaton()':
../src/rollbackBaton.h:14: error: 'class v8::Persistent<v8::Function, v8::NonCopyablePersistentTraits<v8::Function> >' has no member named 'Dispose'
../src/connection.cpp: In static member function 'static void Connection::Init(v8::Handlev8::Object)':
../src/connection.cpp:19: error: no matching function for call to 'v8::FunctionTemplate::New(uni::CallbackType (&)(const uni::FunctionCallbackInfo&))'
/root/.node-gyp/0.12.7/deps/v8/include/v8.h:3455: note: candidates are: static v8::Localv8::FunctionTemplate v8::FunctionTemplate::New(v8::Isolate_, void (_)(const v8::FunctionCallbackInfov8::Value&), v8::Handlev8::Value, v8::Handlev8::Signature, int)
../src/connection.cpp:22: error: 'NewSymbol' is not a member of 'v8::String'
../src/connection.cpp:35: error: 'NewSymbol' is not a member of 'v8::String'
